// Generated by AI, welcome to contribute and improve it!
import { useRef } from "react";
import './css/toast.scss';

class ActionRemoveToast { }
class ActionRedirect2Url {
  url: string;

  constructor(url: string) {
    this.url = url;
  }
}

export const ToastType = {
  Normal: "normal",
  Info: "info",
  Success: "success",
  Warn: "warn",
  Error: "error",
  Debug: "debug",
} as const;

export type ToastType = typeof ToastType[keyof typeof ToastType];

export const ToastOnclickAction = {
  RemoveToast: new ActionRemoveToast(),
  Redirect2Url: (url: string) => (new ActionRedirect2Url(url))
}

const activeToasts: { element: HTMLElement; height: number }[] = [];

const updateToastPositions = () => {
  let accumulatedHeight: number = 60;
  activeToasts.forEach((toast: { element: HTMLElement; height: number }) => {
    const topPosition: number = accumulatedHeight;
    toast.element.style.top = `${topPosition}px`;
    accumulatedHeight += toast.height + 10;
  });
};

const removeToast = (toastElement: HTMLElement) => {
  const index = activeToasts.findIndex(t => t.element === toastElement);
  if (index !== -1) {
    toastElement.classList.add('toast-exit');
    activeToasts.splice(index, 1);

    setTimeout(() => {
      toastElement.remove();
      updateToastPositions();
    }, 300);
  }
};


export interface ToastOptions {
  onClick?: ActionRedirect2Url | ActionRemoveToast;
  type?: ToastType;
  duration?: number;
}

const showToast_ = ( // 竟让我手动操作DOM
  content: string,
  {
    onClick = ToastOnclickAction.RemoveToast,
    type = ToastType.Normal,
    duration = 2000,
  }: ToastOptions = {}
) => {
  const toastElement = document.createElement('div');
  toastElement.className = 'toast-notification';
  const parag = document.createElement("p");
  parag.textContent = content;
  if (onClick instanceof ActionRedirect2Url) {
    parag.style.textDecoration = 'underline';
    parag.style.textDecorationStyle = 'dotted';
    parag.style.textUnderlineOffset = '4px';
  }
  toastElement.appendChild(parag);

  toastElement.style.setProperty('--toast-duration', `${(duration - 300) / 1000}s`);
  toastElement.style.opacity = '0';
  toastElement.style.visibility = 'hidden';
  document.body.appendChild(toastElement);

  const height = toastElement.offsetHeight;

  const toastItem = { element: toastElement, height };
  activeToasts.unshift(toastItem);

  updateToastPositions();

  toastElement.style.opacity = '';
  toastElement.style.visibility = '';
  toastElement.classList.add('toast-enter');
  if (type != ToastType.Normal) {
    toastElement.classList.add(type);
  }

  setTimeout(() => {
    toastElement.classList.remove('toast-enter');
  }, 300);

  const timeoutId = setTimeout(() => {
    removeToast(toastElement);
  }, duration);

  toastElement.addEventListener('click', (e) => {
    if ((e.target as HTMLElement).closest('.toast-context-menu')) {
      return;
    }

    if (onClick instanceof ActionRedirect2Url) {
      window.open(onClick.url, '_blank');
    } else if (onClick instanceof ActionRemoveToast) {
      clearTimeout(timeoutId);
      removeToast(toastElement);
    }
  });

  toastElement.addEventListener('contextmenu', (e) => {
    e.preventDefault();

    clearTimeout(timeoutId);
    removeToast(toastElement);
  });

  return {
    close: () => {
      clearTimeout(timeoutId);
      removeToast(toastElement);
    }
  };
};

export const showToast = {
  // showToast调用方法:
  // --- 组件函数顶层请使用Hook
  // --- 否则使用nohook
  nohook: showToast_,
  Hook: ( // React项目标准: 所有的hooks要么use开头, 要么首字母大写
    content: string,
    options: ToastOptions = {}
  ) => {
    const hasShown = useRef<boolean>(false);
    if (!hasShown.current) {
      hasShown.current = true;
      showToast_(content, options);
    }
  }
}
